[tool.poetry]
name = "aoctemplate"
version = "0.1.0"
description = ""
authors = ["wesoree <wesleylo174@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
panda3d = "^1.10.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
